name: Qodana
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  qodana:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.1.0
